### ISSUE TITLE
Equivalent for WorkItemFormService available?

### ISSUE THREAD

**Issue by Michaelvsk** [Microsoft/azure-devops-extension-api#3]
Hi,
is this SDK already ready to use? I want to create a work item form control extension but couldn't find the WorkfItemFormService (or similar) of the former vss-web-extension-sdk. Due to bug Microsoft/vss-web-extension-sdk#88, which prevented be from using react in my project, I was hoping I can use this SDK already.

Unfortunately the currently provided examples don't show how to create a work item form extension.

**Comment by mohitbagra** [comment]
WorkItemFormService is not yet compatible with the new extension sdk. It is in our backlog but it may not land within next couple of months due to holidays

**Comment by Michaelvsk** [comment]
Thanks for the fast response. Ok then I have to continue my effort to get vss-web-extension-sdk to work with react. :)

**Comment by Gareon** [comment]
> WorkItemFormService is not yet compatible with the new extension sdk. It is in our backlog but it may not land within next couple of months due to holidays

Is there a timeline yet? 

And: Can you please document currently unsupported features or just remove the interface declarations and ids? Since there is no indication that it was not supported, and the interfaces are already available, I just wasted over 8 hours trying to figure out why `getService<WorkItemFormService>(...)` returns `unknown` ...

Thank you.
